"""harness-v1.8: the evidence-driven diagnosis (owner, 2026-10-07: "the fixable_by / 'human must supply' text must be derived from the record's evidence, not a
fixed sentence per class"), the docker / conda stops (T9), the classifier's evidence line (T10) and NLTK as missing data (D-54).

Three layers:
  1. THE KEY. `reports/dev/v18/diagnosis_key.json` was committed before `diagnosis.py` existed, from facts verified in the triage. Each of the 14 blocker records of the
     21 held-out entries (now DEV-CONTAMINATED) is regenerated by `blocker.report` and judged by the key's regexes. On the harness-v1.7.2 code every one of the nine
     "was wrong" entries fails (the old text is a fixed per-class sentence).
  2. THE RULES, on small inputs, with the negative cases that keep a rule from firing on a keyword (`docker` in a comment, `Resource` in another library's message).
  3. THE PLUMBING: the stop-early pipeline, `derived_record` carrying `indeterminate_reason`, the classifier's evidence line.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

from app.services import blocker, classifier, diagnosis, entry_blockers
from app.services.orchestrator import derived_record
from test_d24_build_essential import _fail, _pipeline

ROOT = Path(__file__).resolve().parents[2]
KEY = json.loads((ROOT / "reports" / "dev" / "v18" / "diagnosis_key.json").read_text(encoding="utf-8"))["entries"]


def _record(rel: str) -> dict:
    d = json.loads((ROOT / rel).read_text(encoding="utf-8"))
    if "result" in d:
        r, cert = d["result"], d["certificate"]
        return {"verdict": r["verdict"], "error_chain": r["error_chain"], "attempts": r["attempts"], "indeterminate_reason": r.get("indeterminate_reason") or "",
                "baseline": cert.get("baseline"), "full_log": cert.get("full_log")}
    return {"verdict": d["verdict"], "error_chain": d["error_chain"], "attempts": d["diffs"], "indeterminate_reason": d.get("indeterminate_reason") or "",
            "baseline": d.get("baseline"), "full_log": d.get("full_log")}


def _evidence(rec: dict) -> str:
    return "\n".join(t for _, t in diagnosis._Ctx(rec).blobs)


# --------------------------------------------------------------------------------------------------------------------- 1. the key

@pytest.mark.parametrize("entry", KEY, ids=[e["id"] for e in KEY])
def test_the_regenerated_text_is_right_by_the_pre_committed_key(entry):
    rec = _record(entry["record"])
    out = blocker.report(rec)
    text = f"{out['what_a_human_must_supply']} {out['next_action']}"
    for pattern in entry["must"]:
        assert re.search(pattern, text), f"{entry['id']}: {pattern!r} not in {text!r}"
    for pattern in entry["must_not"]:
        assert not re.search(pattern, text), f"{entry['id']}: {pattern!r} must not be in {text!r}"
    assert out["fixable_by"] in entry["fixable_by"], (entry["id"], out["fixable_by"])
    assert re.search(entry["error_line"], out["error_line"]), (entry["id"], out["error_line"])
    # every quoted line is a line of the record's own output (ANSI colour codes removed), never a paraphrase
    blob = diagnosis.strip_ansi(_evidence(rec))
    gate = "\n".join(str(a.get("gate_violations")) for a in rec["attempts"])  # what the gate said about the attempts (stored as text)
    assert out["error_line"].strip() in blob
    for b in out["basis"]:
        assert b["quote"].strip() in blob or b["quote"].strip() in gate, b


def test_the_nine_old_texts_were_wrong_by_the_same_key():
    """The key and the triage agree: the text harness-v1.7.x stored for the nine "was wrong" entries fails the key."""
    failures = 0
    for entry in (e for e in KEY if e["kind"] == "was_wrong"):
        d = json.loads((ROOT / entry["record"]).read_text(encoding="utf-8"))
        stored = (d["result"] if "result" in d else d).get("blocker") or {}
        text = stored.get("what_a_human_must_supply", "")
        bad = (any(not re.search(p, text) for p in entry["must"]) or any(re.search(p, text) for p in entry["must_not"])
               or stored.get("fixable_by") not in entry["fixable_by"])
        failures += bool(bad)
    assert failures == 9


def test_a_default_is_marked_as_a_default():
    out = blocker.report({"verdict": "BLOCKED", "attempts": [], "error_chain": [
        {"error": "ZeroDivisionError: division by zero", "class": "RUNTIME_ERROR_OTHER", "attribution": "REPO", "phase": "repo_run", "cleared_by": None}]})
    assert out["diagnosis"] == "class_default" and out["cause"] == "RUNTIME_ERROR_OTHER"
    assert out["error_line"] == "ZeroDivisionError: division by zero" and out["next_action"] == out["what_a_human_must_supply"]


# --------------------------------------------------------------------------------------------------------------------- 2. the rules

def _chain(error: str, cls: str = "RUNTIME_ERROR_OTHER", phase: str = "repo_run") -> list[dict]:
    return [{"error": error, "class": cls, "attribution": "REPO", "phase": phase, "cleared_by": None}]


def _attempt(n: int = 1, stderr: str = "", env=(), gate: str = "[]") -> dict:
    return {"attempt_number": str(n), "diff_text": "", "gate_decision": "PASS", "gate_violations": gate, "exit_code": 1, "stdout_tail": "", "stderr_tail": stderr,
            "env_delta": list(env), "origin": "model"}


def test_docker_names_the_missing_container_runtime_and_prefers_the_recorded_line():
    rec = {"verdict": "BLOCKED", "error_chain": _chain("run.sh: 7: docker: not found"), "attempts": [_attempt(stderr="docker: Cannot connect to the Docker daemon at unix:///x.sock")]}
    f = diagnosis.diagnose(rec)
    assert f.cause == "DOCKER_REQUIRED" and f.fixable_by == "platform" and f.error_line == "run.sh: 7: docker: not found" and "`run.sh`" in f.sentence


def test_docker_in_a_comment_or_a_word_is_not_docker():
    rec = {"verdict": "BLOCKED", "error_chain": _chain("ValueError: dockerized runs are not supported here"), "attempts": []}
    assert diagnosis.diagnose(rec) is None


def test_conda_names_the_package_pip_cannot_provide_when_the_record_shows_it():
    rec = {"verdict": "BLOCKED", "attempts": [], "error_chain": _chain("install.sh: 3: conda: not found", "SYS_LIB_MISSING") + _chain(
        "ERROR: Could not find a version that satisfies the requirement graph_tool (from versions: none)", "DEP_NOT_ON_PYPI")}
    f = diagnosis.diagnose(rec)
    assert f.cause == "CONDA_REQUIRED" and "graph_tool" in f.sentence and f.error_line == "install.sh: 3: conda: not found"
    bare = diagnosis.diagnose({"verdict": "BLOCKED", "attempts": [], "error_chain": _chain("install.sh: 3: conda: not found", "SYS_LIB_MISSING")})
    assert bare.cause == "CONDA_REQUIRED" and "no distribution on PyPI" not in bare.sentence


def test_argparse_rejection_names_the_nearest_option_the_script_defines():
    err = ("usage: t.py [-h] [--config_path CONFIG_PATH] [--n_devices N]\n"
           "t.py: error: unrecognized arguments: --config a.yml")
    f = diagnosis.diagnose({"verdict": "BLOCKED", "error_chain": _chain("SystemExit: 2"), "attempts": [_attempt(stderr=err)]})
    assert f.cause == "DOCUMENTED_COMMAND_REJECTED" and "`--config_path`" in f.sentence and f.error_line == "t.py: error: unrecognized arguments: --config a.yml"
    far = diagnosis.diagnose({"verdict": "BLOCKED", "error_chain": _chain("SystemExit: 2"),
                              "attempts": [_attempt(stderr="usage: t.py [-h] [--lr LR]\nt.py: error: unrecognized arguments: --zzzzzz 1")]})
    assert "does not define `--zzzzzz`" in far.sentence  # no near option: it says so and does not invent one


def test_nltk_stub_versus_an_ordinary_missing_nltk_package():
    stub = diagnosis.diagnose({"verdict": "BLOCKED", "attempts": [], "error_chain": _chain("Resource \x1b[93mptb\x1b[0m not found.")})
    assert stub.cause == "NLTK_RESOURCE_LICENSED" and "stub" in stub.sentence and stub.error_line == "Resource ptb not found."
    punkt = diagnosis.diagnose({"verdict": "BLOCKED", "attempts": [], "error_chain": _chain("Resource \x1b[93mpunkt\x1b[0m not found.")})
    assert punkt.cause == "NLTK_RESOURCE_MISSING" and "nltk.downloader punkt" in punkt.next_action


def test_resource_not_found_without_any_sign_of_nltk_is_left_alone():
    assert diagnosis.diagnose({"verdict": "BLOCKED", "attempts": [], "error_chain": _chain("RuntimeError: Resource foo not found in the registry")}) is None


def test_mujoco_says_which_release_the_bindings_expected():
    tail = "Exception:\n  You appear to be missing MuJoCo.  We expected to find the file here: /root/.mujoco/mujoco210\n  This package only provides python bindings\n"
    f = diagnosis.diagnose({"verdict": "BLOCKED", "error_chain": _chain("ModuleNotFoundError: No module named 'mujoco_py'", "DEP_MISSING"), "attempts": [_attempt(stderr=tail)]})
    assert f.cause == "MUJOCO_LIBRARY_MISSING" and "2.1" in f.sentence and "mujoco210" in f.sentence and "free to download" in f.next_action


def test_embedded_runtime_modules_are_not_pypi_problems():
    f = diagnosis.diagnose({"verdict": "BLOCKED", "attempts": [], "error_chain": _chain("AttributeError: module 'hou.node' has no attribute 'foo'", "API_REMOVED")})
    assert f.cause == "EMBEDDED_RUNTIME_REQUIRED" and "Houdini" in f.sentence
    assert diagnosis.diagnose({"verdict": "BLOCKED", "attempts": [], "error_chain": _chain("AttributeError: module 'numpy' has no attribute 'float'", "API_REMOVED")}) is None
    # review, finding 4: `maya` and `mathutils` are real, unrelated PyPI projects (a datetime library, a vector library): no claim about a host application
    for name in ("maya", "mathutils"):
        assert diagnosis.diagnose({"verdict": "BLOCKED", "attempts": [], "error_chain": _chain(f"ModuleNotFoundError: No module named '{name}'", "DEP_MISSING")}) is None


def test_a_missing_repository_extension_needs_the_gates_own_message():
    chain = _chain("ModuleNotFoundError: No module named 'ops._ext'", "DEP_MISSING")
    gate = "[{'rule': 'ENV_SHADOWS_REPO_MODULE', 'reason': \"env_delta[0]: 'ops' matches the repository's own module 'ops'; installing an unrelated PyPI package\"}]"
    f = diagnosis.diagnose({"verdict": "BLOCKED", "error_chain": chain, "attempts": [_attempt(gate=gate)]})
    assert f.cause == "REPO_EXTENSION_NOT_BUILT" and "`ops` is the repository's own package" in f.sentence
    assert diagnosis.diagnose({"verdict": "BLOCKED", "error_chain": chain, "attempts": []}) is None  # a dotted name alone proves nothing about the repository


def test_a_missing_module_with_no_pypi_release_versus_one_that_does_not_build():
    chain = _chain("ModuleNotFoundError: No module named 'foo'", "DEP_MISSING")
    add = [{"op": "add", "package": "foo", "version": "1.0"}]
    no_dist = diagnosis.diagnose({"verdict": "BLOCKED", "error_chain": chain, "attempts": [_attempt(stderr="ERROR: No matching distribution found for foo==1.0", env=add)]})
    assert no_dist.cause == "MODULE_NOT_ON_PYPI" and "no installable release" in no_dist.sentence
    bad = diagnosis.diagnose({"verdict": "BLOCKED", "error_chain": chain, "attempts": [_attempt(stderr="  File \"x.py\", line 2\nSyntaxError: invalid syntax", env=add)]})
    assert bad.cause == "VENDORED_MODULE_MISSING"
    nothing = diagnosis.diagnose({"verdict": "BLOCKED", "error_chain": chain, "attempts": [_attempt(stderr="Successfully installed foo-1.0", env=add)]})
    assert nothing is None  # an install that worked says nothing about the module being vendored


def test_the_retired_git_protocol_needs_both_the_failure_and_the_url():
    tail = "  Running command git clone --quiet git://github.com/a/b.git /tmp/x\n  fatal: unable to connect to github.com:\n"
    f = diagnosis.diagnose({"verdict": "BLOCKED", "error_chain": _chain("error: subprocess-exited-with-error", "DEP_BUILD_FAILED"), "attempts": [_attempt(stderr=tail)]})
    assert f.cause == "GIT_PROTOCOL_RETIRED" and "git+https://github.com/" in f.next_action and f.error_line == "fatal: unable to connect to github.com:"
    no_url = diagnosis.diagnose({"verdict": "BLOCKED", "error_chain": _chain("x", "DEP_BUILD_FAILED"), "attempts": [_attempt(stderr="fatal: unable to connect to github.com:\n")]})
    assert no_url is None


@pytest.mark.parametrize("pin, final", [("torchvision==0.6.0a0", "0.6.0"), ("torch==1.5.0rc1", "1.5.0"), ("foo==2.0.0.dev3", "2.0.0")])
def test_prerelease_pins_name_their_final_release(pin, final):
    err = f"ERROR: Could not find a version that satisfies the requirement {pin} (from versions: 0.1)"
    f = diagnosis.diagnose({"verdict": "INDETERMINATE", "attempts": [], "error_chain": _chain(err, "DEP_YANKED", "runner_setup")})
    assert f.cause == "PRERELEASE_PIN_UNAVAILABLE" and f"`{pin.split('==')[0]}=={final}`" in f.next_action


def test_a_final_release_that_is_missing_is_not_a_prerelease_pin():
    err = "ERROR: Could not find a version that satisfies the requirement foo==1.2.3 (from versions: 1.0)"
    assert diagnosis.diagnose({"verdict": "BLOCKED", "attempts": [], "error_chain": _chain(err, "DEP_YANKED")}) is None


def test_an_era_pair_needs_a_pin_that_moved_the_error():
    chain = _chain("AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv2_METHOD'", "API_REMOVED")
    pin = [{"op": "add", "package": "pyOpenSSL", "version": "19.1.0"}]
    moved = _attempt(3, stderr="  File \".../OpenSSL/crypto.py\", line 7\nAttributeError: module 'lib' has no attribute 'GEN_EMAIL'\n", env=pin)
    f = diagnosis.diagnose({"verdict": "BLOCKED", "error_chain": chain, "attempts": [moved]})
    assert f.cause == "ERA_PAIR_MISMATCH" and "GEN_EMAIL" in f.sentence and "pyOpenSSL==19.1.0" in f.sentence
    same = _attempt(3, stderr="AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv2_METHOD'\n", env=pin)
    assert diagnosis.diagnose({"verdict": "BLOCKED", "error_chain": chain, "attempts": [same]}) is None  # the pin changed nothing: no claim about a pair


def test_every_rule_returns_a_verbatim_error_line():
    """For every committed record with a blocker (all harness versions), a finding's error_line is a line of that record's own output."""
    checked = 0
    for p in sorted((ROOT / "runs").glob("**/*.json")):
        if p.stat().st_size > 30_000_000:
            continue
        try:
            d = json.loads(p.read_text(encoding="utf-8"))
        except ValueError:
            continue
        if not isinstance(d, dict):
            continue
        if "result" in d and isinstance(d["result"], dict) and "error_chain" in d["result"]:
            rec = _record(str(p.relative_to(ROOT)))
        elif "diffs" in d and "error_chain" in d:
            rec = _record(str(p.relative_to(ROOT)))
        else:
            continue
        if rec["verdict"] in ("RUNS_CLEAN", "RUNS_AFTER_REPAIR"):
            continue
        finding = diagnosis.diagnose(rec)
        if finding is None:
            continue
        checked += 1
        blob = diagnosis.strip_ansi(_evidence(rec)) + "\n" + diagnosis.strip_ansi(json.dumps(rec.get("attempts"), ensure_ascii=False))
        assert finding.error_line.strip() in blob, (p.name, finding.error_line)
    assert checked >= 14


# --------------------------------------------------------------------------------------------------------------------- 3. the plumbing

def test_docker_at_the_baseline_stops_the_run_with_no_repair(tmp_path):
    result, repair = _pipeline(tmp_path, [_fail("start.sh: 27: docker: not found\n")])
    assert result.verdict == "INDETERMINATE" and result.indeterminate_reason.startswith("DOCKER_REQUIRED:") and repair.calls == []
    b = result.blocker
    assert b["cause"] == "DOCKER_REQUIRED" and b["fixable_by"] == "platform" and b["error_line"] == "start.sh: 27: docker: not found"
    assert b["family"] == "Resources" and b["diagnosis"] == "evidence" and "Docker" in b["next_action"]


def test_conda_at_the_baseline_stops_the_run_with_no_repair(tmp_path):
    result, repair = _pipeline(tmp_path, [_fail("install.sh: 3: conda: not found\n")])
    assert result.verdict == "INDETERMINATE" and result.indeterminate_reason.startswith("CONDA_REQUIRED:") and repair.calls == []
    assert result.blocker["cause"] == "CONDA_REQUIRED"


def test_the_stop_only_reads_the_end_of_the_output():
    noisy = "docker: not found\n" + "\n".join(f"line {i}" for i in range(60)) + "\nValueError: something else\n"
    assert entry_blockers.stop_of(1, "", noisy) is None


def test_a_stored_indeterminate_stop_now_carries_a_blocker():
    """Until v1.7.2 `derived_record` never gave `blocker.report` the reason, so the out-of-sample scan's AutoDoc and mud-pi records have `blocker: null`."""
    reason = "ENTRYPOINT_NEEDS_ARGS: the command failed because it did not get the arguments it reads (`main.py: error: the following arguments are required: -file`); a human must supply them"
    out = derived_record("INDETERMINATE", [], [], reason, None)["blocker"]
    assert out["class"] == "ENTRYPOINT_NEEDS_ARGS" and out["error_line"] == "main.py: error: the following arguments are required: -file"
    unclear = derived_record("INDETERMINATE", [], [], "ENTRYPOINT_UNCLEAR: no runnable entrypoint discoverable in recon: no candidate scripts found", None)["blocker"]
    assert unclear["class"] == "ENTRYPOINT_UNCLEAR" and unclear["fixable_by"] == "human" and "name the command" in unclear["next_action"]


# --------------------------------------------------------------------------------------------------------------------- T10 and D-54 (classifier)

def test_pips_wrapper_line_is_not_the_evidence_when_the_cause_precedes_it():
    stderr = ("  Running command git clone --filter=blob:none --quiet git://github.com/a/b.git /tmp/pip-x\n"
              "  fatal: unable to connect to github.com:\n  github.com[0: 140.82.121.3]: errno=Connection timed out\n\n"
              "  error: subprocess-exited-with-error\n  \n  × git clone git://github.com/a/b.git did not run successfully.\n  │ exit code: 128\n"
              "  ╰─> See above for output.\n\nerror: subprocess-exited-with-error\n")
    c = classifier.classify(1, stderr, "")
    assert c.code == "DEP_BUILD_FAILED" and c.evidence == "fatal: unable to connect to github.com:"


def test_a_build_block_with_an_exception_line_keeps_it():
    stderr = "  error: subprocess-exited-with-error\n  Traceback (most recent call last):\n    File \"setup.py\", line 3\n  ValueError: bad metadata\nerror: metadata-generation-failed\n"
    assert classifier.classify(1, stderr, "").evidence == "ValueError: bad metadata"


def test_the_wrapper_alone_stays_the_wrapper():
    assert classifier.classify(1, "  error: subprocess-exited-with-error\n", "").evidence == "error: subprocess-exited-with-error"


def test_system_exit_status_is_not_the_cause_when_the_program_printed_one():
    stderr = ("usage: t.py [-h]\nt.py: error: unrecognized arguments: --config x.yml\n"
              "RERUN_EXIT_HOOK: sys.exit(2) was called; the exit site (most recent call last):\n  File \"t.py\", line 62, in main\nSystemExit: 2\n")
    assert classifier.classify(2, stderr, "").evidence == "t.py: error: unrecognized arguments: --config x.yml"
    assert classifier.classify(2, "Traceback (most recent call last):\n  File \"t.py\", line 1\nSystemExit: 2\n", "").evidence == "SystemExit: 2"


def test_nltk_missing_resource_is_missing_data_not_a_code_error():
    c = classifier.classify(1, "LookupError: \n**********\n  Resource \x1b[93mptb\x1b[0m not found.\n  Please use the NLTK Downloader to obtain the resource:\n", "")
    assert c.code == "DATA_MISSING" and "ptb" in c.evidence
