"""Which Python can install the repository's torch pin (harness-v1.5.1, F1; failure class: a pinned old torch has no wheel for the interpreter RERUN chose).

The Python policy (python_policy) picks 3.10 for a repository that declares nothing. A repository that pins `torch==1.2.0` then fails in the runner's own setup step
(`No matching distribution found for torch==1.2.0`, INDETERMINATE RUNNER_SETUP_FAILED, no repair attempt) because torch 1.2.0's wheels exist for CPython 3.5-3.7 only. The pin is
the repository's own claim about its environment, so the interpreter follows it: among the minors that have a python:X-slim image AND that the repository's own Python declaration
allows (a declared `>=3.10` is never overridden into 3.9), the one the policy prefers FIRST (python_policy.PREFERENCE) that has a Linux x86_64 wheel on the PyTorch CPU index for some
torch release satisfying the pin. The data is a dated snapshot of that index (torch_wheels_data, generated by scripts/build_torch_wheel_table.py), so the decision is reproducible and
tested offline. A pin that the chosen Python can already install, that no release in the snapshot satisfies, that sits in a comment, or whose pin and declared Python cannot both
be met, changes nothing (the run then ends as it did before this rule).
"""

from __future__ import annotations

import re
from typing import Iterable

from app.services import python_policy, runner_env
from app.services.torch_wheels_data import RETRIEVED, SOURCE, WHEELS

SOURCE_NOTE = f"{SOURCE} (snapshot {RETRIEVED})"
# pip's rule: a `#` starts a comment at the start of a line or after whitespace (`git+https://...#egg=torch` keeps its fragment)
_COMMENT = re.compile(r"(^|\s)#.*$", re.M)


def _specifier_set(spec: str):
    try:
        from packaging.specifiers import SpecifierSet

        return SpecifierSet(spec.replace(" ", ""))
    except Exception:  # noqa: BLE001 - an unparseable spec (or no `packaging`) is not a usable pin
        return None


def torch_pin(texts: Iterable[str]) -> str:
    """The torch requirement spec ('==1.2.0', '<1.9.0', '' for none) found in requirement-like texts, with comments removed first: a commented-out line is not the repository's pin."""
    return runner_env.torch_specs(_COMMENT.sub("", t or "") for t in texts).get("torch", "")


def releases_matching(spec: str) -> list[str]:
    """The torch releases in the snapshot that satisfy `spec` (`==1.2.0`, `<1.9`, `>=1.0,<1.5`, `~=1.4`), oldest first. A bare name / empty spec matches every release."""
    try:
        from packaging.version import InvalidVersion, Version
    except Exception:  # noqa: BLE001 - no `packaging`: no decision
        return []
    specs = _specifier_set(spec or "")
    if specs is None:
        return []
    out = []
    for ver in WHEELS:
        try:
            if specs.contains(Version(ver), prereleases=True):
                out.append(ver)
        except InvalidVersion:  # pragma: no cover - the generator only writes parseable versions
            continue
    return sorted(out, key=Version)


def minors_with_wheel(spec: str) -> tuple[str, ...]:
    """The CPython minors for which some release satisfying `spec` has a wheel on the CPU index, in the policy's order of preference."""
    have = {minor for ver in releases_matching(spec) for minor in WHEELS[ver]}
    return tuple(m for m in python_policy.PREFERENCE if m in have)


def newest_release(spec: str, minor: str) -> str | None:
    """The newest release satisfying `spec` that has a wheel for `minor`, or None."""
    try:
        return next((v for v in reversed(releases_matching(spec)) if minor in WHEELS[v]), None)
    except Exception:  # noqa: BLE001 - never a reason to fail a run
        return None


def python_for_pin(choice: python_policy.PythonChoice, spec: str) -> python_policy.PythonChoice:
    """`choice` itself when the pin is empty, installable on the chosen Python, not in the snapshot at all, or not installable on any Python the repository's declaration allows;
    otherwise a choice of the preferred Python that can install it."""
    if not spec:
        return choice
    minors = minors_with_wheel(spec)
    if not minors or choice.version in minors:
        return choice
    with_wheel = minors
    if choice.is_declared:
        allowed = set(python_policy.satisfying_minors(choice.declared or ""))
        if allowed:  # a declaration the policy could parse: the pin may not move the interpreter outside it
            minors = tuple(m for m in minors if m in allowed)
            if not minors:
                return choice
    pick = minors[0]
    release = newest_release(spec, pick)
    reason = (f"the repository pins torch{spec}, which has no wheel on the CPU index for Python {choice.version} (it has them for {', '.join(sorted(with_wheel, key=lambda m: int(m.split('.')[1])))}; "
              f"{SOURCE_NOTE}); the interpreter follows the pin: {pick} (newest matching release with a wheel: torch {release}). Before this rule: {choice.reason}")
    return python_policy.PythonChoice(pick, "torch pin", f"torch{spec}", reason)
