"""Build backend/app/services/torch_wheels_data.py from a saved copy of the PyTorch CPU wheel index (harness-v1.5.1, F1).

    curl -s -o torch_cpu_index.html https://download.pytorch.org/whl/cpu/torch/
    backend/.venv/Scripts/python.exe scripts/build_torch_wheel_table.py torch_cpu_index.html 2026-10-02 > backend/app/services/torch_wheels_data.py

The table says, for every torch release that has a Linux x86_64 wheel on the CPU index (the index the runner installs from, runner_env.CPU_INDEX), which CPython minors that wheel
exists for. Only minors that have a python:X-slim image (python_policy.SUPPORTED, 3.6-3.13) are kept. It is a SNAPSHOT: the runner does not read the index at run time, so
a run is reproducible and the policy is testable offline. Regenerate it (and re-seal) to change it.
"""
from __future__ import annotations

import re
import sys
from collections import defaultdict
from pathlib import Path

SOURCE = "https://download.pytorch.org/whl/cpu/torch/"
SUPPORTED = ("3.6", "3.7", "3.8", "3.9", "3.10", "3.11", "3.12", "3.13")
# torch-1.8.1%2Bcpu-cp39-cp39-linux_x86_64.whl  /  torch-1.2.0%2Bcpu-cp37-cp37m-manylinux1_x86_64.whl  /  torch-1.1.0-cp37-cp37m-linux_x86_64.whl
_WHEEL = re.compile(r">torch-(?P<ver>\d+(?:\.\d+)*(?:\.post\d+)?)(?:\+cpu|%2Bcpu)?-cp(?P<tag>\d+)-cp\d+m?u?-(?:linux_x86_64|manylinux[\w.]*_x86_64)\.whl<")


def minor_of(tag: str) -> str | None:
    """'39' -> '3.9', '310' -> '3.10', '27' -> None (Python 2 has no minor of the 3.x series)."""
    if not tag.startswith("3") or len(tag) < 2:
        return None
    return f"3.{tag[1:]}"


def table(html: str) -> dict[str, tuple[str, ...]]:
    found: dict[str, set[str]] = defaultdict(set)
    for m in _WHEEL.finditer(html):
        minor = minor_of(m.group("tag"))
        if minor in SUPPORTED:
            found[m.group("ver")].add(minor)
    return {ver: tuple(sorted(minors, key=lambda s: int(s.split(".")[1]))) for ver, minors in found.items()}


def _version_key(ver: str) -> tuple:
    return tuple(int(p) if p.isdigit() else 0 for p in re.split(r"[.]|post", ver) if p != "")


def render(html: str, retrieved: str) -> str:
    rows = table(html)
    lines = ['"""Generated by scripts/build_torch_wheel_table.py: which CPython minors have a Linux x86_64 torch wheel on the PyTorch CPU index (harness-v1.5.1, F1). Do not edit."""', "",
             f"SOURCE = {SOURCE!r}", f"RETRIEVED = {retrieved!r}", "", "WHEELS: dict[str, tuple[str, ...]] = {"]
    for ver in sorted(rows, key=_version_key):
        lines.append(f"    {ver!r}: {rows[ver]!r},")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    sys.stdout.write(render(Path(argv[1]).read_text(encoding="utf-8"), argv[2]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
