"""Summarize a finished RERUN batch into a markdown report a judge can re-derive.

    PYTHONPATH=backend python scripts/summarize_batch.py \
        --records runs/corpus_v2_batch/harness-v1.2 --out reports/corpus-v2/summary.md

Every number is computed from the raw per-entry records (the JSON files the batch
driver wrote); nothing is typed by hand. The PRIMARY lines come from the driver's own
pure `summarize()` so the report cannot disagree with `summary.json`.

Definitions used here (also stated in the generated report):
  * error chain: the ordered `[classifier] CODE: message` lines of an entry's full log,
    consecutive duplicates collapsed. Errors that are RERUN's own (patch that failed to
    apply, upload cap, infra) are not classifier lines and never enter the chain.
  * first error: chain[0]. last error: chain[-1].
  * "Tavily cited": at least one attempt carries `tavily_sources` (a Tavily result the
    repair actually used in a decision). Resolver-cited PyPI/git releases are shown in a
    separate column because they did not come from Tavily.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

from run_corpus_v1_batch import load_records, summarize  # noqa: E402

from app.services import error_chain as ec  # noqa: E402  (needs PYTHONPATH=backend until phase 5)

CLASSIFIER_LINE = re.compile(r"^\[classifier\] (?P<code>[A-Z_]+): (?P<msg>.*)$")
TORCH_LAST = re.compile(r"No module named 'torch'")


def error_chain(record: dict) -> list[tuple[str, str]]:
    log = (record.get("certificate") or {}).get("full_log") or ""
    chain: list[tuple[str, str]] = []
    for line in log.splitlines():
        m = CLASSIFIER_LINE.match(line.strip())
        if m and (not chain or chain[-1] != (m["code"], m["msg"])):
            chain.append((m["code"], m["msg"]))
    return chain


def chain_of(record: dict) -> ec.ErrorChain:
    """The run's error chain: stored on records from harness-v1.3 on; rebuilt from the
    `[classifier]` log lines for older records (attribution rules in error_chain.py)."""
    stored = (record.get("result") or {}).get("error_chain")
    if stored is not None:
        chain = ec.ErrorChain()
        chain.links = [dict(link) for link in stored]
        return chain
    cert = record.get("certificate") or {}
    intake = record.get("intake") or {}
    return ec.chain_from_log(
        cert.get("full_log") or "",
        declared_deps=frozenset(intake.get("declared_dependencies") or ()),
        python_claim=None,
        base_image=(cert.get("build_plan") or {}).get("base_image"),
    )


def repair_attempts(record: dict) -> int:
    diffs = (record.get("certificate") or {}).get("diffs") or []
    return sum(1 for a in diffs if a.get("origin") != "time_machine")


def tavily_cited(record: dict) -> bool:
    diffs = (record.get("certificate") or {}).get("diffs") or []
    return any(a.get("tavily_sources") for a in diffs)


def resolver_cited(record: dict) -> bool:
    diffs = (record.get("certificate") or {}).get("diffs") or []
    return any(a.get("resolved_sources") for a in diffs)


def cell(text: str, width: int = 90) -> str:
    text = text.replace("|", "\\|").replace("\n", " ")
    return text if len(text) <= width else text[: width - 1] + "…"


def build_report(records: list[dict], summary: dict, records_dir: str, expected: int,
                 annotations: dict[int, str] | None = None, integrity_md: str = "", title: str = "") -> str:
    annotations = annotations or {}
    by_id = {r["batch"]["entry_id"]: r for r in records}
    lines = [f"# {title or 'Batch summary'} — `{records_dir}`", ""]
    if records:
        b = records[0]["batch"]
        lines += [f"corpus `{b['corpus']}` · corpus hash `{b['corpus_hash']}` · harness `{b['harness_tag']}` "
                  f"(`{b['harness_commit'][:8]}`) · generated by `scripts/summarize_batch.py` from the raw records", ""]

    lines += ["## Results", "",
              "| # | entry | verdict | failure class | first repo error | attribution | repair attempts | Tavily cited | resolver cited | spent USD | note |",
              "|--:|---|---|---|---|---|--:|:-:|:-:|--:|---|"]
    for row in summary["rows"]:
        r = by_id[row["id"]]
        chain = chain_of(r)
        attribution = "/".join(dict.fromkeys(link["attribution"] for link in chain.links)) or "—"
        lines.append(
            f"| {row['id']} | {row['name']} | {row['verdict']} | {row['taxonomy_code'] or row['reason_code'] or '—'} "
            f"| {cell(chain.first_repo_error or '—', 60)} | {attribution} | {repair_attempts(r)} | {'Y' if tavily_cited(r) else 'N'} | {'Y' if resolver_cited(r) else 'N'} "
            f"| {row['spent_usd']:.2f} | {annotations.get(row['id'], '')} |")
    lines.append("")

    p = summary["primary"]
    lines += ["## PRIMARY", "",
              f"- `{p['headline']}` — runs-after-repair / failed-as-published, of PRIMARY entries "
              f"(driver `summarize()` in `scripts/run_corpus_v1_batch.py`).",
              f"- `PRIMARY measured: {p['n_measured']} of {p['n']}` — failed as published {p['failed_as_published']}, "
              f"ran as published {p['ran_as_published']}; excluded as RERUN's own: invalid_harness "
              f"{p['invalid_harness']}, infra_error {p['infra_error']}, upload_too_large {p['upload_too_large']}, "
              f"pipeline_error {p['pipeline_error']}.",
              f"- verdicts: {json.dumps(p['verdicts'])}",
              f"- blocked by reason: {json.dumps(p['blocked_by_reason'])}", ""]

    done = len(records)
    lines += [f"STATUS: {done} of {expected} records present; total spent ${summary['total_spent_usd']:.2f}; "
              f"verdicts {json.dumps(p['verdicts'])}", ""]

    lines += ["## Failure attribution", "",
              "For every BLOCKED entry: the **first** error the classifier saw and the **last** one, plus the whole "
              "chain. The verdict's own failure class is the *last* error's class, which after repair attempts can be "
              "a different (often runner-side) problem than the first. First error = chain[0]; see the module "
              "docstring for the definition.", "",
              "| # | entry | first error | last error | chain length |",
              "|--:|---|---|---|--:|"]
    torch_last = 0
    torch_entries = []
    for row in summary["rows"]:
        if row["verdict"] != "BLOCKED":
            continue
        chain = error_chain(by_id[row["id"]])
        if not chain:
            first = last = "(no classifier line)"
        else:
            first = f"{chain[0][0]}: {chain[0][1]}"
            last = f"{chain[-1][0]}: {chain[-1][1]}"
        if chain and chain[-1][0] == "DEP_MISSING" and TORCH_LAST.search(chain[-1][1]):
            torch_last += 1
            torch_entries.append(row["id"])
        lines.append(f"| {row['id']} | {row['name']} | {cell(first)} | {cell(last)} | {len(chain)} |")
    lines += ["", f"**Entries that ended in `DEP_MISSING: torch`: {torch_last}**"
              + (f" (entries {', '.join(map(str, torch_entries))})" if torch_entries else ""), ""]

    if integrity_md:
        lines += ["## Run integrity", "", integrity_md.strip(), ""]

    lines += ["## Not counted as verdicts about the repository", ""]
    ours = [row for row in summary["rows"] if row["verdict"] in ("UPLOAD_TOO_LARGE", "INFRA_ERROR", "INVALID_HARNESS")]
    if ours:
        for row in ours:
            lines.append(f"- #{row['id']} {row['name']}: `{row['verdict']}` (RERUN-side limit, not evidence about the paper)")
    else:
        lines.append("- none")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--records", required=True, type=Path, help="directory of NN_*.json batch records")
    ap.add_argument("--out", required=True, type=Path)
    ap.add_argument("--expected", type=int, default=20, help="entries the corpus defines (for the STATUS line)")
    ap.add_argument("--annotations", type=Path, help="JSON {entry_id: note} shown in the table's note column")
    ap.add_argument("--integrity", type=Path, help="markdown inlined as the 'Run integrity' section")
    ap.add_argument("--title", default="")
    args = ap.parse_args(argv)
    annotations = ({int(k): v for k, v in json.loads(args.annotations.read_text(encoding="utf-8")).items()}
                   if args.annotations else {})
    integrity = args.integrity.read_text(encoding="utf-8") if args.integrity else ""
    records = load_records(args.records)
    if not records:
        print(f"no records in {args.records}", file=sys.stderr)
        return 2
    summary = summarize(records)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(build_report(records, summary, args.records.as_posix(), args.expected, annotations, integrity, args.title), encoding="utf-8", newline="\n")
    print(f"wrote {args.out} ({len(records)} records)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
